const assert=require('assert');const store=new Map(),files=new Map(),toasts=[];let capturedPage=null,sharedFile=null,chooseFile=null,relaunchUrl='',modalConfirm=true;
const clone=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v));
function applyPath(target,path,value){const parts=path.split('.');let c=target;for(let i=0;i<parts.length-1;i++){if(!c[parts[i]]||typeof c[parts[i]]!=='object')c[parts[i]]={};c=c[parts[i]];}c[parts.at(-1)]=value;}
global.wx={env:{USER_DATA_PATH:'/user-data'},getStorageSync:k=>store.has(k)?clone(store.get(k)):'',setStorageSync:(k,v)=>store.set(k,clone(v)),removeStorageSync:k=>store.delete(k),showToast:o=>toasts.push(o&&o.title),showModal:o=>o&&o.success&&o.success({confirm:modalConfirm,cancel:!modalConfirm}),navigateBack(){},reLaunch:o=>{relaunchUrl=o&&o.url;},setNavigationBarColor(){},getFileSystemManager(){return{writeFile(o){files.set(o.filePath,String(o.data));o.success&&o.success();},readFile(o){files.has(o.filePath)?o.success&&o.success({data:files.get(o.filePath)}):o.fail&&o.fail({errMsg:'not found'});}}},shareFileMessage(o){sharedFile={filePath:o.filePath,fileName:o.fileName};o.success&&o.success();},chooseMessageFile(o){chooseFile?o.success&&o.success({tempFiles:[chooseFile]}):o.fail&&o.fail({errMsg:'chooseMessageFile:fail cancel'});}};
global.Page=d=>capturedPage=d;['../utils/storage','../utils/model','../utils/theme','../pages/settings/settings'].forEach(p=>{try{delete require.cache[require.resolve(p)]}catch{}});const storage=require('../utils/storage'),model=require('../utils/model');require('../pages/settings/settings');
function page(){const p={};Object.entries(capturedPage).forEach(([k,v])=>p[k]=k==='data'?clone(v):v);p.setData=function(x,cb){Object.entries(x||{}).forEach(([k,v])=>k.includes('.')?applyPath(this.data,k,v):this.data[k]=v);cb&&cb.call(this);};return p;}
storage.clearAll();storage.saveConfiguration(model.normalizeSettings({birth_date:'2000-06-18',target_age:80,mode:'advanced',expense_mode:'manual',manual_daily_expense:50,theme:'paper',font_family:'serif',font_scale:'large'}),30000,'2026-08-01',true);storage.addTransaction({occurred_on:'2026-08-20',type:'expense',amount:100,note:'午餐'});
const p=page();p.onLoad();p.exportBackup();assert.strictEqual(p.data.backupBusy,false);assert(sharedFile&&files.has(sharedFile.filePath));const exported=JSON.parse(files.get(sharedFile.filePath));assert.strictEqual(exported.transactions.length,2);
// Unsaved setting must block export instead of exporting stale storage.
p.setData({'form.manual_daily_expense':'77'});sharedFile=null;p.exportBackup();assert.strictEqual(sharedFile,null);assert(toasts.some(x=>String(x).includes('未保存改动')));p.setData({'form.manual_daily_expense':50});
// restore from selected chat file
storage.saveSettings(model.normalizeSettings({birth_date:'1999-01-01',target_age:90,mode:'quick',manual_daily_expense:999}));storage.saveTransactions([]);files.set('/tmp/restore.json',JSON.stringify(exported));chooseFile={path:'/tmp/restore.json',size:Buffer.byteLength(files.get('/tmp/restore.json'))};p.importBackup();assert.strictEqual(storage.getTransactions().length,2);assert.strictEqual(storage.getSettings().birth_date,'2000-06-18');assert.strictEqual(relaunchUrl,'');
files.set('/tmp/bad.json','{"schema":"other","version":1,"transactions":[]}');chooseFile={path:'/tmp/bad.json',size:files.get('/tmp/bad.json').length};const before=JSON.stringify(storage.getTransactions());p.importBackup();assert.strictEqual(JSON.stringify(storage.getTransactions()),before);assert(p.data.backupHint.includes('不是有效'));
chooseFile={path:'/tmp/huge.json',size:storage.MAX_BACKUP_FILE_BYTES+1};p.importBackup();assert(p.data.backupHint.includes('过大'));
chooseFile=null;p.importBackup();assert.strictEqual(p.data.backupBusy,false);
console.log('settings_backup_ui.test.js: PASS');
