from pathlib import Path
from playwright.sync_api import sync_playwright
import json, os, time
ROOT=Path(__file__).resolve().parents[2]
RENDERER=(ROOT/'utils'/'ritual_grid.js').read_text(encoding='utf-8')
OUT=Path(__file__).resolve().parent/'screens_v042_final';OUT.mkdir(parents=True,exist_ok=True)
CSS=r'''*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;font-family:-apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif}.overlay{position:fixed;inset:0;background:#06070b;color:#f4efe5;overflow:hidden}.stage{position:absolute;inset:0;background:#06070b}canvas{width:100%;height:100%;display:block}.topveil,.bottomveil{position:absolute;left:0;right:0;pointer-events:none}.topveil{top:0;height:112px;background:linear-gradient(180deg,rgba(5,6,10,.96),rgba(5,6,10,.58),transparent)}.bottomveil{bottom:0;height:160px;background:linear-gradient(0deg,rgba(5,6,10,.98),rgba(5,6,10,.64),transparent)}.head{position:absolute;z-index:3;left:15px;right:14px;top:38px;display:flex;justify-content:space-between;align-items:flex-start}.eyebrow{font-size:9px;letter-spacing:2px;color:#957d43}.title{margin-top:5px;font-size:18px;line-height:1.28;font-weight:650;color:#f5d981}.out .title{color:#d9b3a4}.skip{height:29px;padding:0 14px;border-radius:9px;border:1px solid rgba(255,255,255,.07);background:rgba(255,255,255,.05);color:#8f929b}.foot{position:absolute;z-index:3;left:16px;right:16px;bottom:28px}.count{display:flex;align-items:baseline;gap:7px}.num{font-size:38px;line-height:1;font-weight:700;color:#f3ce68}.out .num{color:#d7aa99}.unit{font-size:12px;color:#858891}.copy{margin-top:9px;display:flex;justify-content:space-between;gap:10px;font-size:10px}.copy span:first-child{color:#a3a5ab}.copy span:last-child{text-align:right;color:#666a74}.paper{background:#e9e1d5;color:#302820}.paper .stage{background:#e5ddcf}.paper .topveil{background:linear-gradient(180deg,rgba(233,225,213,.98),rgba(233,225,213,.72),transparent)}.paper .bottomveil{background:linear-gradient(0deg,rgba(233,225,213,.99),rgba(233,225,213,.76),transparent)}.paper .eyebrow{color:#92702f}.paper .title{color:#8e631e}.paper .num{color:#9b691d}.paper .unit{color:#756b60}.paper .copy span:first-child{color:#66594c}.paper .copy span:last-child{color:#8a7f72}.paper .skip{border-color:rgba(75,58,38,.08);background:rgba(75,58,38,.06);color:#75695c}'''
def page_html(kind='ignite',theme='midnight'):
 paper=theme=='paper'
 return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>{CSS}</style><script>var module={{exports:{{}}}};{RENDERER}</script></head><body><div id="overlay" class="overlay{' paper' if paper else ''}{' out' if kind=='extinguish' else ''}"><div id="stage" class="stage"><canvas id="canvas"></canvas></div><div class="topveil"></div><div class="bottomveil"></div><div class="head"><div><div class="eyebrow">{'BUY BACK YOUR TIME' if kind=='ignite' else 'TIME REPRICED'}</div><div class="title">{'点亮 12 天自由' if kind=='ignite' else '熄灭 12 天自由'}</div></div><button class="skip">跳过</button></div><div class="foot"><div class="count"><span class="num" id="num">{'100' if kind=='ignite' else '112'}</span><span class="unit">天自由</span></div><div class="copy"><span id="live">镜头正在寻找新的自由边界</span><span id="progress">共 12 天</span></div></div></div><script>
const lib=module.exports,kind='{kind}',paper={str(paper).lower()};const palette=paper?{{background:'#e5ddcf',unlit:'#cfc4b4',lit:'#a8741f',asset:'#58769a',bloom:'#fff3d2',ash:'#8f7868',ember:'#a65f4d',past:'#d9d0c3',trackedPast:'#9b8e78'}}:{{background:'#0b0e13',unlit:'#292d35',lit:'#ffd166',asset:'#9cc3ff',bloom:'#fff4d6',ash:'#5a4030',ember:'#d77957',past:'#1a1d23',trackedPast:'#343126'}};let before,after;if(kind==='ignite'){{before={{total_cells:20000,future_cells:20000,past_cells:0,tracked_past_cells:0,asset_lit:0,income_lit:100,lit_count:100}};after={{...before,income_lit:112,lit_count:112}}}}else{{before={{total_cells:20000,future_cells:20000,past_cells:0,tracked_past_cells:0,asset_lit:0,income_lit:112,lit_count:112}};after={{...before,income_lit:100,lit_count:100}}}}const c=document.getElementById('canvas'),stage=document.getElementById('stage');function off(w,h){{let x=document.createElement('canvas');x.width=w;x.height=h;return x}}async function go(){{let r=stage.getBoundingClientRect(),e=new lib.RitualGrid(c,{{createOffscreenCanvas:off}});e.resize(r.width,r.height,Math.min(devicePixelRatio||1,2));window.engine=e;let t0=performance.now();let result=await e.run({{before,after,palette,kind,onProgress:(done,all,current,triggered)=>{{num.textContent=current;let active=Math.max(0,(triggered||0)-done);if(done>=all)live.textContent=kind==='ignite'?'这段时间，已经属于你':'新的自由边界已经落定';else if(active>0)live.textContent=`第 ${{Math.min(all,done+1)}} 天 · ${{kind==='ignite'?'正在被点亮':'正在黯淡'}}`;progress.textContent=done>0?(kind==='ignite'?`已买回 ${{done}} / ${{all}} 天`:`已退回 ${{done}} / ${{all}} 天`):`共 ${{all}} 天`;}}}});window.__done=true;window.__result={{...result,wall:Math.round(performance.now()-t0)}}}}requestAnimationFrame(go);</script></body></html>'''
scenarios=[('ignite_midnight_390',390,844,'ignite','midnight',[250,650,1300,3400,5900,7800]),('extinguish_midnight_390',390,844,'extinguish','midnight',[250,650,1600,4200,7200,9800]),('ignite_small_320',320,568,'ignite','midnight',[250,1300,3400,5900]),('ignite_paper_390',390,844,'ignite','paper',[250,1300,3400,5900])]
perf={}
with sync_playwright() as pw:
 b=pw.chromium.launch(headless=True,executable_path='/usr/bin/chromium',args=['--no-sandbox'])
 for name,w,h,k,t,times in scenarios:
  p=b.new_page(viewport={'width':w,'height':h});p.set_content(page_html(k,t),wait_until='load');last=0
  for i,at in enumerate(times):p.wait_for_timeout(at-last);last=at;p.screenshot(path=str(OUT/f'{name}_f{i}.png'))
  p.wait_for_function('window.__done===true',timeout=20000);perf[name]=p.evaluate('window.__result');p.close()
 b.close()
(OUT/'performance.json').write_text(json.dumps(perf,ensure_ascii=False,indent=2),encoding='utf-8');print(json.dumps(perf,ensure_ascii=False,indent=2))
